import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Providers } from "./providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rwiddhi Mitra Portfolio",
  description: "Generated by love",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="min-h-screen bg-gradient-to-b from-[#c8acef] to-[#4f5397] text-white">

            <header className="h-24">
              <Navbar />
            </header>

            <main className="min-h-[calc(100vh-6rem)] flex items-center justify-center">
              {children}
            </main>

          </div>
        </Providers>
      </body>
    </html>
  );
}
