import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Providers } from "./providers";
import { LenisProvider } from "../context/LenisContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rwiddhi Mitra Portfolio",
  description: "Generated by love",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <Providers>
        <LenisProvider>

        <div
        className="
        fixed
        top-0
        left-0
        right-0
        z-50
        flex
        justify-center
        pt-6
        pointer-events-none
        "
        >

        <div className="pointer-events-auto w-full flex justify-center">

        <Navbar/>

        </div>

        </div>

          <main className="pt-20">
            {children}
          </main>

        </LenisProvider>
      </Providers>
    </body>
    </html>
  );
}
